// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"zjhx.com/live/api/chat"
	"zjhx.com/live/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext,hub *chat.Hub) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/live/closePublish",
				Handler: ClosePublishHandler(serverCtx,hub),
			},
			{
				Method:  http.MethodGet,
				Path:    "/live/startPublish",
				Handler: StartPublishHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/live/createRoom",
				Handler: CreateRoomHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/live/joinRoom",
				Handler: JoinRoomHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/live/liveList",
				Handler: GetLiveListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/live/saveLive",
				Handler: SaveLiveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
