// Code generated by goctl. DO NOT EDIT.
package types

type MergeReponse struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	Idx      int    `json:"idx"`
	RecordId int    `json:"record_id"`
}

type MergeRequest struct {
	Md5            string `json:"md5"`
	Total          string `json:"total"`
	FileName       string `json:"filename"`
	UserId         string `json:"user_id"`
	DataType       string `json:"type"`
	SourceLanguage string `json:"source_language"`
	DestLanguage   string `json:"dest_language"`
}

type UploadLargeVideoReponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UploadUrlRequest struct {
	Url    string `json:"url"`
	UserId int64  `json:"user_id"`
}

type UploadUrlResponse struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	RecordId int    `json:"record_id"`
}

type UploadVideoReponse struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	RecordId int    `json:"record_id"`
}

type UploadVideoRequest struct {
	FileName string `json:"filename"`
	UserId   int64  `json:"user_id"`
}
