// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"zjhx.com/voice/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/voice/save",
				Handler: SaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/voice/trans",
				Handler: TransHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
