// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
	Token  Token  `json:'token'`
	UserId int64  `json:'user_id'`
	Name   string `json:'name'`
	Avatar string `json:'avatar'`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
}

type RegisterResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UploadImageResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Url  string `json:"url"`
}

type User struct {
	Id              uint32 `json:"id"`
	Name            string `json:"name"`
	Avatar          string `json:"avatar"`
	Signature       string `json:"signature"`
	BackgroundImage string `json:"background_image"` //用户个人页顶部大图
	FollowCount     uint32 `json:"follow_count"`
	FollowerCount   uint32 `json:"follower_count"`
	TotalFavorited  uint32 `json:"total_favorited"`
	WorkCount       uint32 `json:"work_count"`
	FavoriteCount   uint32 `json:"favorite_count"`
	IsFollow        bool   `json:"is_follow"`
}

type UserInfoRequest struct {
	UserId   int64 `form:"user_id"`
	ActionId int64 `form:"action_id"`
}

type UserInfoResponse struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	UserInfo User   `json:"userInfo"`
}
