// Code generated by goctl. DO NOT EDIT.
// Source: voice.proto

package server

import (
	"context"

	"zjhx.com/voice/rpc/internal/logic"
	"zjhx.com/voice/rpc/internal/svc"
	"zjhx.com/voice/rpc/voice"
)

type VoiceServer struct {
	svcCtx *svc.ServiceContext
	voice.UnimplementedVoiceServer
}

func NewVoiceServer(svcCtx *svc.ServiceContext) *VoiceServer {
	return &VoiceServer{
		svcCtx: svcCtx,
	}
}

// 上传文件创建记录
func (s *VoiceServer) UploadVoice(ctx context.Context, in *voice.UploadRequest) (*voice.UploadResponse, error) {
	l := logic.NewUploadVoiceLogic(ctx, s.svcCtx)
	return l.UploadVoice(in)
}
