// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: voice.proto

package voice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Voice_UploadVoice_FullMethodName = "/voice.Voice/UploadVoice"
)

// VoiceClient is the client API for Voice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceClient interface {
	// 上传文件创建记录
	UploadVoice(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
}

type voiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceClient(cc grpc.ClientConnInterface) VoiceClient {
	return &voiceClient{cc}
}

func (c *voiceClient) UploadVoice(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, Voice_UploadVoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceServer is the server API for Voice service.
// All implementations must embed UnimplementedVoiceServer
// for forward compatibility
type VoiceServer interface {
	// 上传文件创建记录
	UploadVoice(context.Context, *UploadRequest) (*UploadResponse, error)
	mustEmbedUnimplementedVoiceServer()
}

// UnimplementedVoiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoiceServer struct {
}

func (UnimplementedVoiceServer) UploadVoice(context.Context, *UploadRequest) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadVoice not implemented")
}
func (UnimplementedVoiceServer) mustEmbedUnimplementedVoiceServer() {}

// UnsafeVoiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceServer will
// result in compilation errors.
type UnsafeVoiceServer interface {
	mustEmbedUnimplementedVoiceServer()
}

func RegisterVoiceServer(s grpc.ServiceRegistrar, srv VoiceServer) {
	s.RegisterService(&Voice_ServiceDesc, srv)
}

func _Voice_UploadVoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServer).UploadVoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voice_UploadVoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServer).UploadVoice(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Voice_ServiceDesc is the grpc.ServiceDesc for Voice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Voice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.Voice",
	HandlerType: (*VoiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadVoice",
			Handler:    _Voice_UploadVoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice.proto",
}
