// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"context"

	"zjhx.com/file/rpc/file"
	"zjhx.com/file/rpc/internal/logic"
	"zjhx.com/file/rpc/internal/svc"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

// 上传文件创建记录
func (s *FileServer) UploadFile(ctx context.Context, in *file.FileRecord) (*file.UploadResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}
