// Code generated by goctl. DO NOT EDIT.
package types

type SaveRequest struct {
	TextList []string `json:"text"`
}

type SaveResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type TransRequest struct {
	Text string `json:"text"`
	From string `json:"from"`
	To   string `json:"to"`
}

type TransResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}
