// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"zjhx.com/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/video/merge",
				Handler: mergeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/video/upload",
				Handler: uploadVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/video/uploadLarge",
				Handler: uploadLargeVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/video/uploadUrl",
				Handler: uploadUrlHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
