// Code generated by goctl. DO NOT EDIT.
package types

type AiRewritingRequest struct {
	Text []string `json:"text"`
}

type AiRewritingResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}

type RecordByIdRequest struct {
	Id uint64 `form:"id"`
}

type RecordByIdRespone struct {
	Code      int                 `json:"code"`
	Msg       string              `json:"msg"`
	Id        uint64              `json:"id"`
	Path      string              `json:"path"`
	Title     string              `json:"title"`
	UserId    uint64              `json:"user_id"`
	DataType  uint32              `json:"datatype"`
	Keyword   []map[string]string `json:"keyword"`
	Summary   string              `json:"summary"`
	Scanning  []map[string]string `json:"scanning"`
	InnerText map[string]string   `json:"inner_text"`
	Review    []map[string]string `json:"review"`
	TransText []map[string]string `json:"trans_text"`
}

type RecordByUserIdRequest struct {
	UserId uint64 `form:"user_id"`
}

type RecordByUserIdRespone struct {
	SingleRecords []SingleRecord `json:"singlerecords"`
	Code          int            `json:"code"`
	Msg           string         `json:"msg"`
}

type SingleRecord struct {
	Id         uint64 `json:"id"`
	Title      string `json:"title"`
	UpdateTime string `json:"updatetime"`
	Keyword    string `json:"keyword"`
	DataType   uint32 `json:"dataType"`
}
