// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"zjhx.com/record/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/record/getAiRewriting",
				Handler: getAiRewritingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/record/recentRecordById",
				Handler: recentRecordByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/record/recordById",
				Handler: recordByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/record/recordByUserid",
				Handler: recordByUseridHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
